# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4154154ede3161d56e0e0dfe0d51181d18e54c1a5e078989eb4481d9aa93c58228eab8f16a747097a1de51fa1ede94ae2cf8cf9b69fd3b1bfb11d0e206287889

test:
  secret_key_base: bdd6d7dd075a9af488c928582698831f35d40438f96298ae64c9fc146df9b0877100ee198d78b663e507fa3ad2cf031d3518a3516d59de788cd7c012e82c3469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
